data:
  dataset: ADNI
  atlas: cc200
  batch_size: 16
  test_batch_size: 16
  val_batch_size: 16
  train_set: 0.8
  test_set: 0.2
  fold: 0
  time_seires: data/adni_nc_ad.npy
  # time_seires: data/adni_nc_mci.npy
  # time_seires: data/adni_mci_ad.npy 

model:
  name: KMGCN
  extractor_type: attention
  embedding_size: 8
  window_size: 4
  cnn_pool_size: 16
  num_gru_layers: 4
  dropout: 0.5

train:
  lr: 1.0e-4
  weight_decay: 1.0e-4
  epochs: 500
  pool_ratio: 0.7
  optimizer: adam
  stepsize: 200

  group_loss: true
  sparsity_loss: true
  sparsity_loss_weight: 0.5e-4
  log_folder: result
  pure_gnn_graph: pearson
